[tool:pytest]
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')
testpaths = src/test_yt_summarize_bot
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
pythonpath = src